// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOkuQ7ocr9eGbLwjHRn911NYq14J0uWdc',
    appId: '1:263726532845:web:158a8eb16906b2c8f164e4',
    messagingSenderId: '263726532845',
    projectId: 'ncommerceapp',
    authDomain: 'ncommerceapp.firebaseapp.com',
    storageBucket: 'ncommerceapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5Juc9H4sxzyJvReDCvDARbZAYT2zPeY',
    appId: '1:263726532845:android:833ebf63cb989f5ff164e4',
    messagingSenderId: '263726532845',
    projectId: 'ncommerceapp',
    storageBucket: 'ncommerceapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Y80GYnsnO2u6yr-UOgLT6EKrpKaxS50',
    appId: '1:263726532845:ios:a18ccae8d94d701ff164e4',
    messagingSenderId: '263726532845',
    projectId: 'ncommerceapp',
    storageBucket: 'ncommerceapp.firebasestorage.app',
    androidClientId: '263726532845-fdv5ef40irrn6kss9pvm9mr02407rpaj.apps.googleusercontent.com',
    iosClientId: '263726532845-5ah5dlbg6nk5ifpff9053inpbgi78fkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.ninjaStore',
  );

}